// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	"crypto/tls"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

func (_m *Client) GetNumberSentinelSlavesInMemory(ip string, tlsConfig *tls.Config) (int32, error) {
	ret := _m.Called(ip, tlsConfig)

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *tls.Config) (int32, error)); ok {
		return rf(ip, tlsConfig)
	}
	if rf, ok := ret.Get(0).(func(string, *tls.Config) int32); ok {
		r0 = rf(ip, tlsConfig)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if rf, ok := ret.Get(1).(func(string, *tls.Config) error); ok {
		r1 = rf(ip, tlsConfig)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *Client) GetNumberSentinelsInMemory(ip string, tlsConfig *tls.Config) (int32, error) {
	ret := _m.Called(ip, tlsConfig)

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *tls.Config) (int32, error)); ok {
		return rf(ip, tlsConfig)
	}
	if rf, ok := ret.Get(0).(func(string, *tls.Config) int32); ok {
		r0 = rf(ip, tlsConfig)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if rf, ok := ret.Get(1).(func(string, *tls.Config) error); ok {
		r1 = rf(ip, tlsConfig)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *Client) GetSentinelMonitor(ip string, tlsConfig *tls.Config) (string, string, error) {
	ret := _m.Called(ip, tlsConfig)

	var r0, r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, *tls.Config) (string, string, error)); ok {
		return rf(ip, tlsConfig)
	}
	if rf, ok := ret.Get(0).(func(string, *tls.Config) string); ok {
		r0 = rf(ip, tlsConfig)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(string, *tls.Config) string); ok {
		r1 = rf(ip, tlsConfig)
	} else {
		r1 = ret.Get(1).(string)
	}
	if rf, ok := ret.Get(2).(func(string, *tls.Config) error); ok {
		r2 = rf(ip, tlsConfig)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

func (_m *Client) GetSlaveOf(ip string, port string, password string, tlsConfig *tls.Config) (string, error) {
	ret := _m.Called(ip, port, password, tlsConfig)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, *tls.Config) (string, error)); ok {
		return rf(ip, port, password, tlsConfig)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, *tls.Config) string); ok {
		r0 = rf(ip, port, password, tlsConfig)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(string, string, string, *tls.Config) error); ok {
		r1 = rf(ip, port, password, tlsConfig)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *Client) IsMaster(ip string, port string, password string, tlsConfig *tls.Config) (bool, error) {
	ret := _m.Called(ip, port, password, tlsConfig)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, *tls.Config) (bool, error)); ok {
		return rf(ip, port, password, tlsConfig)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, *tls.Config) bool); ok {
		r0 = rf(ip, port, password, tlsConfig)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if rf, ok := ret.Get(1).(func(string, string, string, *tls.Config) error); ok {
		r1 = rf(ip, port, password, tlsConfig)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *Client) MakeMaster(ip string, port string, password string, tlsConfig *tls.Config) error {
	ret := _m.Called(ip, port, password, tlsConfig)
	if rf, ok := ret.Get(0).(func(string, string, string, *tls.Config) error); ok {
		return rf(ip, port, password, tlsConfig)
	}
	return ret.Error(0)
}

func (_m *Client) MakeSlaveOf(ip string, masterIP string, password string, tlsConfig *tls.Config) error {
	ret := _m.Called(ip, masterIP, password, tlsConfig)
	if rf, ok := ret.Get(0).(func(string, string, string, *tls.Config) error); ok {
		return rf(ip, masterIP, password, tlsConfig)
	}
	return ret.Error(0)
}

func (_m *Client) MakeSlaveOfWithPort(ip string, masterIP string, masterPort string, password string, tlsConfig *tls.Config) error {
	ret := _m.Called(ip, masterIP, masterPort, password, tlsConfig)
	if rf, ok := ret.Get(0).(func(string, string, string, string, *tls.Config) error); ok {
		return rf(ip, masterIP, masterPort, password, tlsConfig)
	}
	return ret.Error(0)
}

func (_m *Client) MonitorRedis(ip string, monitor string, quorum string, password string, tlsConfig *tls.Config) error {
	ret := _m.Called(ip, monitor, quorum, password, tlsConfig)
	if rf, ok := ret.Get(0).(func(string, string, string, string, *tls.Config) error); ok {
		return rf(ip, monitor, quorum, password, tlsConfig)
	}
	return ret.Error(0)
}

func (_m *Client) MonitorRedisWithPort(ip string, monitor string, port string, quorum string, password string, tlsConfig *tls.Config) error {
	ret := _m.Called(ip, monitor, port, quorum, password, tlsConfig)
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, *tls.Config) error); ok {
		return rf(ip, monitor, port, quorum, password, tlsConfig)
	}
	return ret.Error(0)
}

func (_m *Client) ResetSentinel(ip string, tlsConfig *tls.Config) error {
	ret := _m.Called(ip, tlsConfig)
	if rf, ok := ret.Get(0).(func(string, *tls.Config) error); ok {
		return rf(ip, tlsConfig)
	}
	return ret.Error(0)
}

func (_m *Client) SentinelCheckQuorum(ip string, tlsConfig *tls.Config) error {
	ret := _m.Called(ip, tlsConfig)
	if rf, ok := ret.Get(0).(func(string, *tls.Config) error); ok {
		return rf(ip, tlsConfig)
	}
	return ret.Error(0)
}

func (_m *Client) SetCustomRedisConfig(ip string, port string, configs []string, password string, tlsConfig *tls.Config) error {
	ret := _m.Called(ip, port, configs, password, tlsConfig)
	if rf, ok := ret.Get(0).(func(string, string, []string, string, *tls.Config) error); ok {
		return rf(ip, port, configs, password, tlsConfig)
	}
	return ret.Error(0)
}

func (_m *Client) SetCustomSentinelConfig(ip string, configs []string, tlsConfig *tls.Config) error {
	ret := _m.Called(ip, configs, tlsConfig)
	if rf, ok := ret.Get(0).(func(string, []string, *tls.Config) error); ok {
		return rf(ip, configs, tlsConfig)
	}
	return ret.Error(0)
}

func (_m *Client) SlaveIsReady(ip string, port string, password string, tlsConfig *tls.Config) (bool, error) {
	ret := _m.Called(ip, port, password, tlsConfig)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, *tls.Config) (bool, error)); ok {
		return rf(ip, port, password, tlsConfig)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, *tls.Config) bool); ok {
		r0 = rf(ip, port, password, tlsConfig)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if rf, ok := ret.Get(1).(func(string, string, string, *tls.Config) error); ok {
		r1 = rf(ip, port, password, tlsConfig)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
